import type { IBoardFilters } from 'src/types/board';
import type { RealtimePaginationQuery } from 'src/__generated__/graphql';

export const POSTITEMS: RealtimePaginationQuery['realtimePagination'] = [
  {
    __typename: 'RealTime',
    boardId: '1',
    rank: '1',
    site: 'Site A',
    title: 'Understanding TypeScript Generics',
    url: 'https://example.com/understanding-typescript-generics',
    createTime: '2024-08-24T14:48:00Z',
    GPTAnswer: 'Generics provide a way to create reusable components.',
  },
  {
    __typename: 'RealTime',
    boardId: '2',
    rank: '2',
    site: 'Site B',
    title: 'React Component Lifecycle Explained',
    url: 'https://example.com/react-component-lifecycle',
    createTime: '2024-08-23T10:30:00Z',
    GPTAnswer:
      "React component lifecycle methods allow you to run code at particular times in a component's existence.",
  },
  {
    __typename: 'RealTime',
    boardId: '3',
    rank: null, // Optional, can be null
    site: 'Site C',
    title: 'GraphQL vs REST: A Comparison',
    url: 'https://example.com/graphql-vs-rest',
    createTime: '2024-08-22T09:15:00Z',
    GPTAnswer: null, // Optional, can be null
  },
  {
    __typename: 'RealTime',
    boardId: '4',
    rank: '3',
    site: 'Site D',
    title: 'How to Optimize Web Performance',
    url: 'https://example.com/optimize-web-performance',
    createTime: '2024-08-21T13:45:00Z',
    GPTAnswer:
      'Optimizing web performance involves improving loading speed, reducing resource consumption, and enhancing the user experience.',
  },
  {
    __typename: 'RealTime',
    boardId: '5',
    rank: '4',
    site: 'Site E',
    title: 'Introduction to Node.js Streams',
    url: 'https://example.com/nodejs-streams',
    createTime: '2024-08-20T08:20:00Z',
    GPTAnswer: 'Node.js streams allow handling of streaming data in a more efficient way.',
  },
  {
    __typename: 'RealTime',
    boardId: '6',
    rank: '5',
    site: 'Site F',
    title: 'Understanding JavaScript Closures',
    url: 'https://example.com/understanding-javascript-closures',
    createTime: '2024-08-19T07:10:00Z',
    GPTAnswer: 'Closures in JavaScript allow functions to have access to their own scope.',
  },
  {
    __typename: 'RealTime',
    boardId: '7',
    rank: '6',
    site: 'Site G',
    title: 'A Guide to CSS Grid',
    url: 'https://example.com/a-guide-to-css-grid',
    createTime: '2024-08-18T06:00:00Z',
    GPTAnswer: 'CSS Grid is a powerful layout system for creating two-dimensional grids.',
  },
  {
    __typename: 'RealTime',
    boardId: '8',
    rank: '7',
    site: 'Site H',
    title: 'The Importance of Code Reviews',
    url: 'https://example.com/the-importance-of-code-reviews',
    createTime: '2024-08-17T04:50:00Z',
    GPTAnswer:
      'Code reviews ensure that the code is maintainable, efficient, and follows best practices.',
  },
  {
    __typename: 'RealTime',
    boardId: '9',
    rank: '8',
    site: 'Site I',
    title: 'Best Practices for Writing Clean Code',
    url: 'https://example.com/best-practices-for-writing-clean-code',
    createTime: '2024-08-16T03:40:00Z',
    GPTAnswer:
      'Writing clean code involves following principles that make the code easy to understand and maintain.',
  },
  {
    __typename: 'RealTime',
    boardId: '10',
    rank: '9',
    site: 'Site J',
    title: 'The Role of DevOps in Modern Software Development',
    url: 'https://example.com/the-role-of-devops-in-modern-software-development',
    createTime: '2024-08-15T02:30:00Z',
    GPTAnswer: 'DevOps practices bridge the gap between development and operations teams.',
  },
  {
    __typename: 'RealTime',
    boardId: '11',
    rank: '10',
    site: 'Site K',
    title: 'An Introduction to Machine Learning',
    url: 'https://example.com/an-introduction-to-machine-learning',
    createTime: '2024-08-14T01:20:00Z',
    GPTAnswer:
      'Machine learning is a subset of artificial intelligence that involves training models on data.',
  },
  {
    __typename: 'RealTime',
    boardId: '12',
    rank: '11',
    site: 'Site L',
    title: 'Understanding WebAssembly',
    url: 'https://example.com/understanding-webassembly',
    createTime: '2024-08-13T00:10:00Z',
    GPTAnswer:
      'WebAssembly is a binary instruction format that allows for platform-agnostic code execution.',
  },
  {
    __typename: 'RealTime',
    boardId: '13',
    rank: '12',
    site: 'Site M',
    title: 'The Benefits of Using a CSS Preprocessor',
    url: 'https://example.com/the-benefits-of-using-a-css-preprocessor',
    createTime: '2024-08-12T23:00:00Z',
    GPTAnswer: 'CSS preprocessors like Sass or Less simplify the process of writing CSS.',
  },
  {
    __typename: 'RealTime',
    boardId: '14',
    rank: '13',
    site: 'Site N',
    title: "A Beginner's Guide to Docker",
    url: 'https://example.com/a-beginners-guide-to-docker',
    createTime: '2024-08-11T21:50:00Z',
    GPTAnswer: 'Docker is a containerization platform that simplifies application deployment.',
  },
  {
    __typename: 'RealTime',
    boardId: '15',
    rank: '14',
    site: 'Site O',
    title: 'The Importance of Accessibility in Web Development',
    url: 'https://example.com/the-importance-of-accessibility-in-web-development',
    createTime: '2024-08-10T20:40:00Z',
    GPTAnswer: 'Accessibility in web development ensures that websites are usable by everyone.',
  },
  {
    __typename: 'RealTime',
    boardId: '16',
    rank: '15',
    site: 'Site P',
    title: 'Understanding the Basics of Cybersecurity',
    url: 'https://example.com/understanding-the-basics-of-cybersecurity',
    createTime: '2024-08-09T19:30:00Z',
    GPTAnswer: 'Cybersecurity involves protecting systems and data from unauthorized access.',
  },
  {
    __typename: 'RealTime',
    boardId: '17',
    rank: '16',
    site: 'Site Q',
    title: 'A Guide to Frontend Build Tools',
    url: 'https://example.com/a-guide-to-frontend-build-tools',
    createTime: '2024-08-08T18:20:00Z',
    GPTAnswer:
      'Frontend build tools like Webpack or Rollup simplify the process of building and managing frontend code.',
  },
  {
    __typename: 'RealTime',
    boardId: '18',
    rank: '17',
    site: 'Site R',
    title: 'The Role of Artificial Intelligence in Healthcare',
    url: 'https://example.com/the-role-of-artificial-intelligence-in-healthcare',
    createTime: '2024-08-07T17:10:00Z',
    GPTAnswer:
      'Artificial intelligence is transforming healthcare by improving diagnosis and treatment.',
  },
  {
    __typename: 'RealTime',
    boardId: '19',
    rank: '18',
    site: 'Site S',
    title: 'Understanding Blockchain Technology',
    url: 'https://example.com/understanding-blockchain-technology',
    createTime: '2024-08-06T16:00:00Z',
    GPTAnswer: 'Blockchain technology enables secure, decentralized, and transparent data storage.',
  },
  {
    __typename: 'RealTime',
    boardId: '20',
    rank: '19',
    site: 'Site T',
    title: 'The Future of Web Development',
    url: 'https://example.com/the-future-of-web-development',
    createTime: '2024-08-05T14:50:00Z',
    GPTAnswer:
      'The future of web development involves advancements in technologies like PWA, AR, and VR.',
  },
  {
    __typename: 'RealTime',
    boardId: '21',
    rank: '20',
    site: 'Site U',
    title: "A Beginner's Guide to Kubernetes",
    url: 'https://example.com/a-beginners-guide-to-kubernetes',
    createTime: '2024-08-04T13:40:00Z',
    GPTAnswer:
      'Kubernetes is a container orchestration system for automating deployment and scaling.',
  },
  {
    __typename: 'RealTime',
    boardId: '22',
    rank: '21',
    site: 'Site V',
    title: 'Understanding Microservices Architecture',
    url: 'https://example.com/understanding-microservices-architecture',
    createTime: '2024-08-03T12:30:00Z',
    GPTAnswer:
      'Microservices architecture involves breaking down a monolithic application into smaller services.',
  },
  {
    __typename: 'RealTime',
    boardId: '23',
    rank: '22',
    site: 'Site W',
    title: 'The Benefits of Using a State Management Library',
    url: 'https://example.com/the-benefits-of-using-a-state-management-library',
    createTime: '2024-08-02T11:20:00Z',
    GPTAnswer:
      'State management libraries like Redux or MobX simplify state management in applications.',
  },
  {
    __typename: 'RealTime',
    boardId: '24',
    rank: '23',
    site: 'Site X',
    title: 'A Guide to Web Performance Optimization',
    url: 'https://example.com/a-guide-to-web-performance-optimization',
    createTime: '2024-08-01T10:10:00Z',
    GPTAnswer:
      'Web performance optimization involves techniques to improve the loading speed of websites.',
  },
  {
    __typename: 'RealTime',
    boardId: '25',
    rank: '24',
    site: 'Site Y',
    title: 'Understanding the Basics of Computer Networks',
    url: 'https://example.com/understanding-the-basics-of-computer-networks',
    createTime: '2024-07-31T09:00:00Z',
    GPTAnswer:
      'Computer networks involve the communication between devices through protocols and hardware.',
  },
];

// 목업 데이터 생성
export const SITE_FILTER: IBoardFilters = {
  site: ['Site A', 'Site B'],
};
